// <auto-generated />
using HierarchicalData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Microsoft.SqlServer.Types;

#nullable disable

namespace HierarchicalData.Migrations
{
    [DbContext(typeof(HierarchicalDataContext))]
    [Migration("20230617095849_InitialCreateHierarchical")]
    partial class InitialCreateHierarchical
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.5.23280.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HierarchicalData.OrganizationPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<SqlHierarchyId>("Path")
                        .HasColumnType("hierarchyid");

                    b.HasKey("Id");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Name = "CEO",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/")
                        },
                        new
                        {
                            Id = -2,
                            Name = "Chief Commercial Officer",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/1/")
                        },
                        new
                        {
                            Id = -3,
                            Name = "Global Retail",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/1/1/")
                        },
                        new
                        {
                            Id = -4,
                            Name = "Enterprise Sales",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/1/2/")
                        },
                        new
                        {
                            Id = -5,
                            Name = "CTO",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/2/")
                        },
                        new
                        {
                            Id = -6,
                            Name = "Head of Software Development",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/2/1/")
                        },
                        new
                        {
                            Id = -7,
                            Name = ".Net Team Lead",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/2/1/1/")
                        },
                        new
                        {
                            Id = -8,
                            Name = ".Net Senior Engineer",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/2/1/1/1/")
                        },
                        new
                        {
                            Id = -9,
                            Name = ".Net Junior Engineer",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/2/1/1/2/")
                        },
                        new
                        {
                            Id = -10,
                            Name = "Frontend Team Lead",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/2/1/2/")
                        },
                        new
                        {
                            Id = -11,
                            Name = "Head of AI, ChatGPT, BlockChain and other buzzwords",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/2/2/")
                        },
                        new
                        {
                            Id = -12,
                            Name = "Chief AI Bot",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/2/2/1/")
                        },
                        new
                        {
                            Id = -13,
                            Name = "Chief Prompt Engineer",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/2/2/2/")
                        },
                        new
                        {
                            Id = -14,
                            Name = "Chief Web3 Developer",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/2/2/3/")
                        },
                        new
                        {
                            Id = -15,
                            Name = "Chief Marketing Officer",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/3/")
                        },
                        new
                        {
                            Id = -16,
                            Name = "Marketing Communications Head",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/3/1/")
                        },
                        new
                        {
                            Id = -17,
                            Name = "Marketing Communications Sr. Officer",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/3/1/1/")
                        },
                        new
                        {
                            Id = -18,
                            Name = "Marketing Social Communications Sr. Officer",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/3/1/2/")
                        },
                        new
                        {
                            Id = -19,
                            Name = "Marketing Communications Jr. Officer",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/3/1/3/")
                        },
                        new
                        {
                            Id = -20,
                            Name = "Marketing Communications Intern",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/3/1/1/1/")
                        },
                        new
                        {
                            Id = -21,
                            Name = "Marketing Advertising Head",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/3/2/")
                        },
                        new
                        {
                            Id = -22,
                            Name = "Advertising Agency Director",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/3/2/1/")
                        },
                        new
                        {
                            Id = -23,
                            Name = "Advertising Agency Specialist",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/3/2/1/1/")
                        },
                        new
                        {
                            Id = -24,
                            Name = "Marketing Brand Head",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/3/3/")
                        },
                        new
                        {
                            Id = -25,
                            Name = "Marketing Brand Manager",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/3/3/1/")
                        },
                        new
                        {
                            Id = -26,
                            Name = "CFO",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/4/")
                        },
                        new
                        {
                            Id = -27,
                            Name = "Corporate Vice President Finances",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/4/1/")
                        },
                        new
                        {
                            Id = -28,
                            Name = "Chief Accountant",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/4/1/1/")
                        },
                        new
                        {
                            Id = -29,
                            Name = "Accounting Manager",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/4/1/1/1/")
                        },
                        new
                        {
                            Id = -30,
                            Name = "Accountant",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/4/1/1/1/1/")
                        },
                        new
                        {
                            Id = -31,
                            Name = "Head of Budgeting",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/4/1/2/")
                        },
                        new
                        {
                            Id = -32,
                            Name = "Finance Analyst",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/4/1/2/1/")
                        },
                        new
                        {
                            Id = -33,
                            Name = "Head of Tax Department",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/4/2/")
                        },
                        new
                        {
                            Id = -34,
                            Name = "Head of Reporting Department",
                            Path = Microsoft.SqlServer.Types.SqlHierarchyId.Parse("/4/2/")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
